### ISSUE TITLE
Type undefined in Safari

### ISSUE THREAD

**Issue by gz81gs** [lourds-n-cie/cyto-acoustics#1]
TypeError: audioCtx.createStereoPanner is not a function. (In 'audioCtx.createStereoPanner()', 'audioCtx.createStereoPanner' is undefined.

when sound is called to be played.

**Comment by tsimbalar** [comment]
Thanks for the bug report.
To be honest, we did not really try to make it work on all browsers ;)

I'll try to have a look when I get a moment, but I expect that's not the only issue we'll have with Safari :P

**Comment by gz81gs** [comment]
I meant to just post as informational. Sorry 'bout that. 

Love the app!

**Comment by tsimbalar** [comment]
haha , thanks ! 

Leaving the issue open to remember to check it out

**Comment by tsimbalar** [comment]
This should be fixed !
